version: '2'

services:
  opps:
    image: daocloud.io/subaru/oppsnet
    restart: always
    container_name: opps
    networks:
      net:
        ipv4_address: 172.31.1.2
    environment:
      - PORT=999
      - VPN_DOMAIN=yourname.com
      - VPN_NETWORK=100.64.1.0
      - VPN_NETMASK=255.255.255.0
      - VPN_USERNAME=yourusername
      - VPN_PASSWORD=yourpassword
      - SS_IP=1.2.3.4
      - SS_PORT=8989
      - SS_PASS=yoursspasswd
      - SS_METHOD=aes-256-cfb
    ports:
      - "10.214.62.242:999:999/tcp"
      - "10.214.62.242:999:999/udp"
    cap_add:
      - NET_ADMIN
    restart: always

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 172.31.1.0/24
        gateway: 172.31.1.1
